spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8203
spring:
  profiles: dev
  application: 
    name: cloud-config-client03
eureka: 
  instance: 
    instance-id: 192.168.0.104:${spring.application.name}:${server.port}
    prefer-ip-address: true
  client: 
    service-url: 
      defaultZone: http://192.168.0.105:7001/eureka,http://192.168.0.105:7002/eureka
testbus: zwx06
---
server: 
  port: 8204
spring:
  profiles: test
  application: 
    name: cloud-config-client03
eureka: 
  instance: 
    instance-id: 192.168.0.105:${spring.application.name}:${server.port}
    prefer-ip-address: true
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
testbus: zwx06
---
server: 
  port: 8203
spring:
  profiles: prod
  application: 
    name: cloud-config-client03
eureka: 
  instance: 
    instance-id: 192.168.0.105:${spring.application.name}:${server.port}
    prefer-ip-address: true
  client: 
    service-url: 
      defaultZone: http://192.168.0.105:7001/eureka,http://192.168.0.105:7002/eureka
testbus: zwx06
