spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8201
spring:
  profiles: dev
  application: 
    name: cloud-config-client02
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
testbus: zwx01
---
server: 
  port: 8202
spring:
  profiles: test
  application: 
    name: cloud-config-client02
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
testbus: zwx01
